version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${gedcom.build.user.name}
builderEmail=${gedcom.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${gedcom.branch}
gitCommitIdDescribe=${gedcom.commit.id.describe}
gitCommitId=${gedcom.commit.id.full}
gitCommitUrl=${gedcom.remote.origin.url}
gitCommitTime=${gedcom.commit.time}
gitDirty=${gedcom.dirty}